plugins {
    id 'maven-publish'
    id 'java'
    id 'com.enonic.xp.app'
}

publishing {
    publications {
        maven(MavenPublication) {
            groupId = "${group}"
            artifactId = "${projectName}"
            version = "${version}"

            from components.java
        }
    }
}

dependencies {
    implementation xplibs.api.core
    implementation xplibs.api.portal
    include xplibs.portal
    include "com.enonic.lib:lib-cache:3.0.0"
}

repositories {
    mavenLocal()
    mavenCentral()
    xp.enonicRepo()
}

wrapper {
    gradleVersion = '9.4.1'
  distributionType = Wrapper.DistributionType.BIN
}
